pipeline {
    agent any
    options {
        timeout(time: 1, unit: 'MINUTES')
    }
  
    stages {
        stage('Inicio de options') {
            steps {
                echo "El pipeline ejecuta una tarea con un timeout de 1 minutos"
            }
        }
        stage('Tarea por tiempo') {
            steps {
                echo "Empezando simulacion de tarea larga..."
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    echo 'Empezando la actividad de error...'
                    sleep(time: 2, unit: 'MINUTES')
                }
            }
        }

        stage('Finalizando') {
            steps {
                echo "Tarea procesada..."
            }
        }
    }

    post {
        failure {
            echo 'EL PIPELINE HA FALLADO, MOTIVO TIMEOUT'
        }
    }
}