pipeline {
    agent any

    triggers {
        upstream(upstreamProjects: 'pipeline-environment', threshold: hudson.model.Result.SUCCESS)
    }
  
    stages {
        stage('Build DESPUES DE CORRER MI PIPELINE ENVIRONMENT') {
            steps {
                echo 'Disparando mi job despues del env..'
            }
        }
    }
}